# Autogenerated by Dotfiles
{
  packageOverrides = pkgs: with pkgs; {
    defaultSystem = pkgs.buildEnv {
      name = "default";
      paths = [
        alacritty
        i3-gaps
        i3lock
        i3status
        i3blocks
        rofi
        feh
        ranger
        highlight
        atool
        ./projects/guibou/nixGL
        neovim
        zsh
        oh-my-zsh
        gh
      ];
    };
  };
}
