sudo apt install -y \
  acpi \
  atool \
  autoconf \
  avrdude \
  cmake \
  feh \
  highlight \
  i3status \
  libbz2-dev \
  libev-dev \
  libffi-dev \
  libfontconfig1-dev \
  libfreetype6-dev \
  liblzma-dev \
  libncurses5-dev \
  libncursesw5-dev \
  libpango1.0-dev \
  libreadline-dev \
  libsqlite3-dev \
  libssl-dev \
  libstartup-notification0-dev \
  libtool \
  libxcb-cursor-dev \
  libxcb-icccm4-dev \
  libxcb-keysyms1-dev \
  libxcb-randr0-dev \
  libxcb-shape0-dev \
  libxcb-util0-dev \
  libxcb-xfixes0-dev \
  libxcb-xinerama0-dev \
  libxcb-xkb-dev \
  libxcb1-dev \
  libxkbcommon-dev \
  libxkbcommon-x11-dev \
  libyajl-dev \
  llvm \
  mediainfo \
  neovim \
  pkg-config \
  poppler-utils \
  python-openssl \
  ranger \
  rofi \
  suckless-tools \
  tk-dev \
  w3m \
  xdotool \
  xutils-dev \
  xz-utils \
  zlib1g-dev \
  zsh