sudo apt install -y \
  acpi \
  atool \
  cmus \
  feh \
  ffmpeg \
  g++ \
  gnutls-bin \
  gperf \
  gtk-doc-tools \
  highlight \
  i3 \
  intltool \
  libbz2-dev \
  libffi-dev \
  libgirepository1.0-dev \
  libglib3.0-cil-dev \
  libgnutls28-dev \
  libgtk-3-dev \
  liblzma-dev \
  libncurses5-dev \
  libncursesw5-dev \
  libpcre2-dev \
  libreadline-dev \
  libsqlite3-dev \
  libssl-dev \
  libxml2-utils \
  llvm \
  mediainfo \
  neofetch \
  neovim \
  poppler-utils \
  python-mutagen \
  python-openssl \
  python3-mutagen \
  ranger \
  tk-dev \
  valac \
  w3m \
  xz-utils \
  youtube-dl \
  zlib1g-dev \
  zsh