import = [
    "/home/ronnie/projects/catppuccin/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[cursor]
unfocused_hollow = true
vi_mode_style = "Block"

[font]
size = 13.0

[shell]
program = "/usr/bin/zsh"
